### ISSUE TITLE
TTF + Project description

### ISSUE THREAD

**Issue by davelab6** [jonpinhorn/shrikhand#12]
- [x] There is no TTF in `build`, nor is there a release ZIP with a TTF in https://github.com/jonpinhorn/shrikhand/releases - either is fine but please add one :)
- [ ] Please add a bit more to README about the project to use in the gf directory specimen

**Comment by davelab6** [comment]
@jonpinhorn eta for the TTF? :)

**Comment by jonpinhorn** [comment]
Hi Dave,

I’m actually working on it right now. I’ll try to get both Shrikhand and Atithi exporting TTF’s from Glyphs.

JP :-)

**Comment by davelab6** [comment]
Awesome!

**Comment by jonpinhorn** [comment]
Hi Dave,

So, after getting through most of the way through the ‘compiling TTF’s’ ourselves we had a couple of problems. Liang’s helped us out with them so the TTF’s are now available on the repositories.

If I’m able to sort Atithi TTF’s out myself then I will. If not I’ll have to wait until Liang is able to compile it for me. I hope this is ok? Atithi is otherwise finished and up-to-date on Github. I did the production work myself, for the first time. :-)

Now, I think it’s just a case of sorting out Atithi's invoice and plans/contracts for April?

Regards,

Jonny

**Comment by davelab6** [comment]
Readme is still a bit messed up from a merge, https://github.com/jonpinhorn/shrikhand/commit/12f0008cb2a8ac33851b1cad5fe1a81a2c82edf1#diff-04c6e90faac2675aa89e2176d2eec7d8R22

**Comment by davelab6** [comment]
TTF added in https://github.com/jonpinhorn/shrikhand/commit/69aa5577b804f4b0e9af46e4ccfedc0f82782d68
